# Generated by Django 2.1.10 on 2019-08-14 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190811_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Category'),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
